import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useAccount } from "wagmi";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	const [address, setAddress] = useState<string | null>(null);

	const { isConnected } = useAccount({
		onConnect: ({ address, isReconnected, connector }) => {
			console.log("Wallet has been connected");
			if (address) {
				setAddress(address);
			} else {
				alert("Wallet not connected");
			}
		},
	});

	const handleClaimClick = () => {
		const timeStamp = new Date().toISOString();
		const alertMessage = `${address} has connected at ${timeStamp}`;
		alert(alertMessage);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>RainbowKit App</title>
				<meta
					content="Generated by @rainbow-me/create-rainbowkit"
					name="description"
				/>
				<link href="/favicon.ico" rel="icon" />
			</Head>

			<main className={styles.main}>
				<nav className={styles.navbar}>
					<span>LOGO</span>
					<ConnectButton />
				</nav>
				<div className={styles.claimButtonContainer}>
					<button
						className={`${styles.claimButton} ${
							!isConnected && styles.disabledClaimButton
						}`}
						onClick={handleClaimClick}
						disabled={!isConnected}
					>
						{isConnected ? "Claim" : "Connect your wallet to claim"}
					</button>
				</div>
			</main>

			<footer className={styles.footer}>
				<a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
					Made with ❤️ by your frens at 🌈
				</a>
			</footer>
		</div>
	);
};

export default Home;
